### PR TITLE
fix: upgrade kotlin-gradle-plugin in vpnLib

### PR DESCRIPTION
**Pull request by Maders**
Fix the #46.

### CODE REVIEW

**Comment by Maders** [comment]
Hey @ccnnde, thanks for merging. I'll appreciate if you published the increased version on NPM. ✌🏻

**Comment by ccnnde** [comment]
I will publish soon 😄

**Comment by ccnnde** [comment]
If you could give me a 🌟, I would greatly appreciate it.

**Comment by ccnnde** [comment]
@Maders v2.1.0 published 🎉

**Pull request merged**
